### ISSUE TITLE
Discord invite link in Readme has expired 

### ISSUE THREAD

**Issue by philippnagel** [xsutD7YBMiZCkgV9uxxJ6Z/movemint#2]
Hello, 

Thanks for doing this!

As indicated by the readme I tried to join your Discord via the given link: https://discord.gg/wXHHxD.

According to Discord this link has expired. I suppose that this is not a permission issue due to the public nature of the readme-file.

Regards,
Phil

**Comment by naolduga** [comment]
Phil, thanks for opening this issue. The (expired) Discord link will be removed from the README until a moderation policy is put in place for the server. Closing this issue for now but please stay tuned for updates. Cheers!
